// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXSv8p-eBL9oyRyinwde5zufSrxT9GxA',
    appId: '1:632351466310:web:8361b586eb2a26dc963b47',
    messagingSenderId: '632351466310',
    projectId: 'taskgdsc',
    authDomain: 'taskgdsc.firebaseapp.com',
    databaseURL: 'https://taskgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskgdsc.appspot.com',
    measurementId: 'G-3GS079YFV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0F76E2XhfFSf7nlaOftln9TZn_ibUcAE',
    appId: '1:632351466310:android:55f08099ea127fd6963b47',
    messagingSenderId: '632351466310',
    projectId: 'taskgdsc',
    databaseURL: 'https://taskgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskgdsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJ0mN3dPhTIb0muTtThV4zfaVveDB56I',
    appId: '1:632351466310:ios:324202d0e5c66c24963b47',
    messagingSenderId: '632351466310',
    projectId: 'taskgdsc',
    databaseURL: 'https://taskgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskgdsc.appspot.com',
    iosClientId: '632351466310-gucep1n91c1nlc5mg2s5cdo4atlaleiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJ0mN3dPhTIb0muTtThV4zfaVveDB56I',
    appId: '1:632351466310:ios:9854f35a5c1cc903963b47',
    messagingSenderId: '632351466310',
    projectId: 'taskgdsc',
    databaseURL: 'https://taskgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskgdsc.appspot.com',
    iosClientId: '632351466310-46eau4k88lisr2ktn8t3d331spi7nhe4.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj3.RunnerTests',
  );
}
